name = "pb"
compatibility_date = "2023-01-28"

account_id = "884a8745a9e75ae72b6b9b52998c1028"
workers_dev = false
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }
route = { pattern = "pb.zyp114514.top", custom_domain = true }
kv_namespaces = [
  { binding = "PB", id = "8851530bdadb4f859eae82d1ca2acd43" },
]

[env.preview]
vars = { ENVIRONMENT = "preview" }
route = { pattern = "pb-pr.zyp114514.top", custom_domain = true }
minify = false

kv_namespaces = [
  { binding = "PB", id = "c14102d4c5d44463ad5f19cf2e7bcf98" }
]

